import type { PublicReviewPreview, Show } from "./types";

export const MOCK_SHOWS: Show[] = [
    {
        id: "m1",
        user_id: "demo",
        media_type: "show",
        title: "Crash Landing on You",
        original_title: "사랑의 불시착",
        genre: ["Romance", "Drama"],
        status: "completed",
        episode_count: 16,
        episodes_watched: 16,
        duration_minutes: null,
        year: 2019,
        country: "South Korea",
        language: "Korean",
        notes: null,
        tags: [],
        is_public: true,
        started_at: null,
        completed_at: null,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-10T00:00:00Z",
    },
    {
        id: "m2",
        user_id: "demo",
        media_type: "show",
        title: "Goblin",
        original_title: "도깨비",
        genre: ["Fantasy", "Romance", "Drama"],
        status: "completed",
        episode_count: 16,
        episodes_watched: 16,
        duration_minutes: null,
        year: 2016,
        country: "South Korea",
        language: "Korean",
        notes: null,
        tags: [],
        is_public: true,
        started_at: null,
        completed_at: null,
        created_at: "2024-01-05T00:00:00Z",
        updated_at: "2024-01-15T00:00:00Z",
    },
    {
        id: "m3",
        user_id: "demo",
        media_type: "show",
        title: "Pachinko",
        original_title: "파친코",
        genre: ["Historical", "Drama", "Family"],
        status: "watching",
        episode_count: 16,
        episodes_watched: 8,
        duration_minutes: null,
        year: 2022,
        country: "South Korea",
        language: "Korean",
        notes: null,
        tags: [],
        is_public: true,
        started_at: null,
        completed_at: null,
        created_at: "2024-02-01T00:00:00Z",
        updated_at: "2024-03-01T00:00:00Z",
    },
    {
        id: "m4",
        user_id: "demo",
        media_type: "show",
        title: "My Mister",
        original_title: "나의 아저씨",
        genre: ["Drama", "Slice of Life"],
        status: "completed",
        episode_count: 16,
        episodes_watched: 16,
        duration_minutes: null,
        year: 2018,
        country: "South Korea",
        language: "Korean",
        notes: null,
        tags: [],
        is_public: true,
        started_at: null,
        completed_at: null,
        created_at: "2024-01-20T00:00:00Z",
        updated_at: "2024-02-01T00:00:00Z",
    },
    {
        id: "m5",
        user_id: "demo",
        media_type: "show",
        title: "Vincenzo",
        original_title: "빈센조",
        genre: ["Crime", "Comedy", "Drama"],
        status: "completed",
        episode_count: 20,
        episodes_watched: 20,
        duration_minutes: null,
        year: 2021,
        country: "South Korea",
        language: "Korean",
        notes: null,
        tags: [],
        is_public: true,
        started_at: null,
        completed_at: null,
        created_at: "2024-02-10T00:00:00Z",
        updated_at: "2024-02-20T00:00:00Z",
    },
    {
        id: "m6",
        user_id: "demo",
        media_type: "show",
        title: "Signal",
        original_title: "시그널",
        genre: ["Thriller", "Crime", "Mystery"],
        status: "completed",
        episode_count: 16,
        episodes_watched: 16,
        duration_minutes: null,
        year: 2016,
        country: "South Korea",
        language: "Korean",
        notes: null,
        tags: [],
        is_public: true,
        started_at: null,
        completed_at: null,
        created_at: "2024-03-01T00:00:00Z",
        updated_at: "2024-03-10T00:00:00Z",
    },
];

export const MOCK_REVIEWS: PublicReviewPreview[] = [
    {
        id: "r1",
        show_id: "m1",
        user_id: "u1",
        rating: 9,
        content_snippet:
            "An absolutely stunning romance that transcends borders. The chemistry between the leads is unmatched.",
        created_at: "2024-03-01T00:00:00Z",
    },
    {
        id: "r2",
        show_id: "m2",
        user_id: "u2",
        rating: 10,
        content_snippet:
            "A masterpiece of fantasy romance. The OST alone is worth a rewatch. Gong Yoo is perfect.",
        created_at: "2024-03-05T00:00:00Z",
    },
    {
        id: "r3",
        show_id: "m4",
        user_id: "u3",
        rating: 10,
        content_snippet:
            "The most emotionally resonant drama I have ever watched. Quiet, deliberate, and deeply human.",
        created_at: "2024-03-10T00:00:00Z",
    },
];
